all:
  hosts:
  children:
    servers:
      hosts:
        wow:
          ansible_host: 192.168.10.21
          ansible_user: wow
          ansible_port: 22
        db:
          ansible_host: 192.168.10.20
          ansible_user: db
          ansible_port: 22