---
# tasks file for grafana-server
- name: Add GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main" 
    state: present
    filename: grafana
  

- name: Apt install
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Ufw allow
  ufw:
    rule: allow
    port: '3000'
    proto: tcp

