---
- name: Create node_exporter User
  user:
    name: "{{ node_exporter_user }}"
    groups: "{{ node_exporter_user }}"
    system: true
    shell: /bin/false
    create_home: false
    append: true


- name: Download
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
  register: _download_binary
  until: _download_binary is succeeded

- name: Unpack
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter"
    remote_src: yes

- name: Propagate binaries
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter"
    dest: "{{ node_exporter_source_file }}"
    mode: 0755
    owner: root
    group: root
    remote_src: yes

- name: Create systemd service
  template:
    src: systemd.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: systemd service enable
  systemd:
    name: node_exporter
    enabled: yes
    

- name: Add ufw allow rule
  ufw:
    rule: allow
    port: "9100"
    proto: tcp
    state: enabled