---
- name: Add apt-key
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present

- name: Add apt repository
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present
    filename: jenkins

- name: Install JDK
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Install jenkins
  apt:
    name: jenkins
    state: present

- name: Register Jenkins daemon
  systemd:
    name: jenkins
    daemon-reload: yes
    enabled: yes
    state: started

- name: Firewall config
  ufw:
    rule: allow
    state: enabled
    port: 8080
    proto: tcp

- name: Register Jenkins unlock code
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: unlock_phrase

- name: Show unlock phrase
  debug:
    msg: Key = "{{unlock_phrase.stdout}}"