---
- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /tmp/Dockerfile
  
- name: Copy config file
  template:
    src: config.j2
    dest: /tmp/prometheus.yml

- name: Create a data container
  docker_image:
    name: prometheus
    build:
      path: /tmp/
    source: build
    state: present

- name: Start Prometheus in Docker
  docker_container:
    name: prometheus
    image: prometheus
    state: started
    restart_policy: always
    recreate: yes
    published_ports:
      - 9090:9090